source 'git@github.com:JiaDingYi/Menta-Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'MentaDemo-Global_Example' do
  pod 'MentaDemo-Global', :path => '../'
  pod 'MentaMediationGlobal'
  pod 'MentaVlionGlobal'
  pod 'MentaVlionGlobalAdapter'
  pod 'MentaBaseGlobal'

  target 'MentaDemo-Global_Tests' do
    inherit! :search_paths

    
  end
end
