# source 'git@github.com:JiaDingYi/Menta-Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'MentaDemo-Global_Example' do
  pod 'MentaDemo-Global', :path => '../'
  
  # pod 'MentaBaseGlobal', :path => '/Users/jdy/Desktop/Menta-Global/MentaBaseGlobal.podspec'
  pod 'MentaBaseGlobal',          '1.0.18'
  pod 'MentaMediationGlobal',     '1.0.18'
  pod 'MentaVlionGlobal',         '1.0.18'
  pod 'MentaVlionGlobalAdapter',  '1.0.18'
  

  target 'MentaDemo-Global_Tests' do
    inherit! :search_paths

    
  end
end
